name: Decrypt file
on: push
jobs:
  decrypt-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt file
        run: gpg --quiet --batch --yes --decrypt -passphrase="$PASSPHRASE" --output $HOME/secret.json secret.json.gpg
        env:
          PASSPHRASE: ${{secrets.PASSPHRASE}}
      - name: Print file contents
        run: cat $HOME/secret.json      